name: Build AP World

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: |
          cd ..
          mv PokemonSnap_Archipelago pokemon_snap
          zip -r pokemon_snap.apworld pokemon_snap
          mv pokemon_snap PokemonSnap_Archipelago
          mv pokemon_snap.apworld /PokemonSnap_Archipelago/
      - name: Attach apworld to release
        uses: softprops/action-gh-release@v3
        with:
          files: pokemon_snap.apworld