name: Build AP World

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Archipelago
        uses: actions/checkout@v6
        with:
          repository: ArchipelagoMW/Archipelago
          path: Archipelago
          ref: 0.6.7
      - name: Install Archipelago Requirements
        run: |
          cd Archipelago
          python -m pip install -r requirements.txt
      - name: Clear worlds folder
        run: find Archipelago/worlds/ -mindepth 1 -type d -exec rm -rf {} +          
      - name: Checkout Pokemon Snap
        uses: actions/checkout@v6
        with:
          path: Archipelago/worlds/pokemon_snap
      - name: Build .apworld
        run: |
          cd Archipelago
          python Launcher.py "Build APWorlds"
      - name: Attach apworld to release
        uses: softprops/action-gh-release@v3
        with:
          files: Archipelago/build/apworlds/pokemon_snap.apworld